export default [
    {
        'name': 'Short Sword',
        'size': '',
        'type': 'Melee',
        'damage': '1d6',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 1000
    },
        {
        'name': 'Long Sword',
        'size': '1h/2h',
        'type': 'Melee',
        'damage': '1d8/1d10',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile',
        'details': '',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 1500
    },
        {
        'name': 'Light Crossbow',
        'size': '2h',
        'type': 'Ranged',
        'damage': '1d8',
        'damageType': 'Piercing',
        'range': '80/320',
        'ammunition': 'bolts',
        'conversion': '',
        'details': 'Loading',
        'misc': '',
        'weight': 5,
        'rarity': 1,
        'cost': 2500
    },
        {
        'name': 'Hand Crossbow',
        'size': '',
        'type': 'Ranged',
        'damage': '1d6',
        'damageType': 'Piercing',
        'range': '30/120',
        'ammunition': 'bolts',
        'conversion': '',
        'details': 'Loading, Light',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 7500
    },
        {
        'name': 'Heavy Crossbow',
        'size': '2h',
        'type': 'Ranged',
        'damage': '1d10',
        'damageType': 'Piercing',
        'range': '100/400',
        'ammunition': 'bolts',
        'conversion': '',
        'details': 'Loading, Heavy',
        'misc': '',
        'weight': 18,
        'rarity': 1,
        'cost': 5000
    },
        {
        'name': 'Long Bow',
        'size': '2h',
        'type': 'Ranged',
        'damage': '1d8',
        'damageType': 'Piercing',
        'range': '150/600',
        'ammunition': 'arrows',
        'conversion': '',
        'details': 'Heavy',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 5000
    },
        {
        'name': 'Short Bow',
        'size': '2h',
        'type': 'Ranged',
        'damage': '1d6',
        'damageType': 'Piercing',
        'range': '80/320',
        'ammunition': 'arrows',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 2500
    },
        {
        'name': 'Mace',
        'size': '',
        'type': 'Melee',
        'damage': '1d6',
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 1000
    },
        {
        'name': 'Cane',
        'size': '1h/2h',
        'type': 'Melee',
        'damage': '1d6',
        'damageType': 'Bludgeoning',
        'range': '5/10',
        'ammunition': '',
        'conversion': 'Reach',
        'details': '',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 1000
    },
        {
        'name': 'Flail',
        'size': '',
        'type': 'Melee',
        'damage': '1d8',
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 1500
    },
        {
        'name': 'Morningstar',
        'size': '',
        'type': 'Melee',
        'damage': '1d8',
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 1500
    },
        {
        'name': 'Rapier',
        'size': '',
        'type': 'Melee',
        'damage': '1d8',
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 2500
    },
        {
        'name': 'Bastard Sword',
        'size': '1h/2h',
        'type': 'Melee',
        'damage': '1d10/1d12',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Versatile, Heavy',
         'misc': '',
        'weight': 6,
        'rarity': 1,
        'cost': 2500
    },
        {
        'name': 'Knuckle Dusters',
        'size': '',
        'type': 'Melee',
        'damage': '1d4',
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Light',
        'misc': 'Hidden: proficiency with sleight of hand if weapon is hidden',
        'weight': 1,
        'rarity': 1,
        'cost': 1000    
        },
            {
        'name': 'Clawed Knuckle Dusters',
        'size': '',
        'type': 'Melee',
        'damage': '1d6',
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse',
        'misc': 'Hidden: proficiency with sleight of hand if weapon is hidden',
        'weight': 1,
        'rarity': 1,
        'cost': 2000
    },
        {
        'name': 'Great Axe',
        'size': '2h',
        'type': 'Melee',
        'damage': '1d12',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Heavy',
        'misc': '',
        'weight': 7,
        'rarity': 1,
        'cost': 3000
    },
        {
        'name': 'Hand Axe',
        'size': '',
        'type': 'Melee',
        'damage': '1d6',
        'damageType': 'Slashing',
        'range': '20/60',
        'ammunition': '',
        'conversion': 'Thrown',
        'details': 'Thrown, Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 500
    },
        {
        'name': 'Halberd',
        'size': '2h',
        'type': 'Melee',
        'damage': '1d10',
        'damageType': 'Slashing',
        'range': '5/10',
        'ammunition': '',
        'conversion': 'Reach',
        'details': 'Heavy',
        'misc': '',
        'weight': 6,
        'rarity': 1,
        'cost': 2000
    },
        {
        'name': 'Polearm',
        'size': '2h',
        'type': 'Melee',
        'damage': '1d10',
        'damageType': 'Piercing',
        'range': '5/10',
        'ammunition': '',
        'conversion': 'Reach',
        'details': 'Heavy',
        'misc': '',
        'weight': 18,
        'rarity': 1,
        'cost': 1500
    },
        {
        'name': 'Dagger',
        'size': '',
        'type': 'Melee',
        'damage': '1d4',
        'damageType': 'Piercing',
        'range': '20/60',
        'ammunition': '',
        'conversion': 'Thrown',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': .5,
        'rarity': 1,
        'cost': 200
    },
        {
        'name': 'Kris',
        'size': '',
        'type': 'Melee',
        'damage': '1d6',
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 500
    },
        {
        'name': 'Whip',
        'size': '',
        'type': 'Melee',
        'damage': '1d4',
        'damageType': 'Slashing',
        'range': '5/10',
        'ammunition': '',
        'conversion': 'Reach',
        'details': 'Finesse',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 200
    },
        {
        'name': 'Sickle',
        'size': '',
        'type': 'Melee',
        'damage': '1d4',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 100
    },
        {
        'name': 'Light Hammer',
        'size': '',
        'type': 'Melee',
        'damage': '1d4',
        'damageType': 'Bludgeoning',
        'range': '20/60',
        'ammunition': '',
        'conversion': 'Thrown',
        'details': 'Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 200
    },
        {
        'name': 'Warhammer',
        'size': '1h/2h',
        'type': 'Melee',
        'damage': '1d8/1d10',
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile',
        'details': '',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 1500
    },
        {
        'name': 'Net',
        'size': '',
        'type': 'Thrown',
        'damage': 'None',
        'damageType': 'None',
        'range': '5/15',
        'ammunition': '',
        'conversion': '',
        'details': 'Special',
        'misc': 'A Large or smaller creature hit by a net is Restrained until it is freed. A net has no Effect on creatures that are formless, or creatures that are Huge or larger. A creature can use its action to make a DC 10 Strength check, freeing itself or another creature within its reach on a success. Dealing 5 slashing damage to the net (AC 10) also frees the creature without harming it, ending the Effect and destroying the net. When you use an action, Bonus Action, or Reaction to Attack with a net, you can make only one Attack regardless of the number of attacks you can normally make.',
        'weight': .5,
        'rarity': 1,
        'cost': 100
    },
        {
        'name': 'Hook',
        'size': '',
        'type': 'Melee',
        'damage': '1d4',
        'damageType': 'Slashing',
        'range': '5/10',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': .5,
        'rarity': 1,
        'cost': 500
    },
        {
        'name': 'Spear',
        'size': '1h/2h',
        'type': 'Melee',
        'damage': '1d6/1d8',
        'damageType': 'Piercing',
        'range': '20/60',
        'ammunition': '',
        'conversion': 'Versatile, Thrown',
        'details': '',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 100
    },
        {
        'name': 'Javelin',
        'size': '',
        'type': 'Melee',
        'damage': '1d6',
        'damageType': 'Piercing',
        'range': '30/120',
        'ammunition': '',
        'conversion': 'Thrown',
        'details': '',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 50
    },
        {
        'name': 'Club',
        'size': '',
        'type': 'Melee',
        'damage': '1d4',
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 50
    },
        {
        'name': 'Glaive',
        'size': '2h',
        'type': 'Melee',
        'damage': '1d10',
        'damageType': 'Slashing',
        'range': '5/10',
        'ammunition': '',
        'conversion': 'Reach',
        'details': 'Heavy',
        'misc': '',
        'weight': 6,
        'rarity': 1,
        'cost': 2000
    },
        {
        'name': 'Quarter Staff',
        'size': '1h/2h',
        'type': 'Melee',
        'damage': '1d6/1d8',
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile',
        'details': '',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 20
    },
        {
        'name': 'Lance',
        'size': '',
        'type': 'Melee',
        'damage': '1d12',
        'damageType': 'Piercing',
        'range': '5/10',
        'ammunition': '',
        'conversion': 'Reach',
        'details': 'Special',
        'misc': 'You have disadvantage when you use a lance to Attack a target within 5 feet of you. Also, a lance requires two hands to wield when you aren’t mounted.',
        'weight': 6,
        'rarity': 1,
        'cost': 1000
    },
        {
        'name': 'Maul',
        'size': '2h',
        'type': 'Melee',
        'damage': '2d6',
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Heavy',
        'misc': '',
        'weight': 10,
        'rarity': 1,
        'cost': 1000
    },
        {
        'name': 'Pike',
        'size': '2h',
        'type': 'Melee',
        'damage': '1d10',
        'damageType': 'Piercing',
        'range': '5/10',
        'ammunition': '',
        'conversion': 'Reach',
        'details': 'Heavy',
        'misc': '',
        'weight': 18,
        'rarity': 1,
        'cost': 500
    },
        {
        'name': 'Scimitar',
        'size': '',
        'type': 'Melee',
        'damage': '1d6',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 2500
    },
        {
        'name': 'Trident',
        'size': '1h/2h',
        'type': 'Melee',
        'damage': '1d6/1d8',
        'ddamageType': 'Piercing',
        'range': '20/60',
        'ammunition': '',
        'conversion': 'Versatile, Thrown',
        'details': '',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 500
    },
        {
        'name': 'War Pick',
        'size': '',
        'type': 'Melee',
        'damage': '1d8',
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 500
    },
        {
        'name': 'Saber',
        'size': '',
        'type': 'Melee',
        'damage': '1d8',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 3500
    },
        {
        'name': 'Claymore',
        'size': '2h',
        'type': 'Melee',
        'damage': '2d8',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Heavy',
        'misc': '',
        'weight': 8,
        'rarity': 3,
        'cost': 10000
    },
        {
        'name': 'Cutlass',
        'size': '',
        'type': 'Melee',
        'damage': '1d8',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 1000
    },
        {
        'name': 'Khopesh',
        'size': '1h/2h',
        'type': 'Melee',
        'damage': '1d6/1d8',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': 2,
        'rarity': 3,
        'cost': 2000
    },
        {
        'name': 'Machete',
        'size': '',
        'type': 'Melee',
        'damage': '1d6/1d8',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile',
        'details': '',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 100
    },
        {
        'name': 'Chakram',
        'size': '',
        'type': 'Melee',
        'damage': '1d8',
        'damageType': 'Slashing',
        'range': '20/60',
        'ammunition': '',
        'conversion': 'Thrown',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 800
    },
        {
        'name': 'Blowgun',
        'size': '',
        'type': 'Ranged',
        'damage': '1',
        'damageType': 'Piercing',
        'range': '25/100',
        'ammunition': 'darts',
        'conversion': '',
        'details': 'Loading',
        'misc': '',
        'weight': 1,
        'rarity': 1,
        'cost': 10
    },
        {
        'name': 'Scythe',
        'size': '1h/2h',
        'type': 'Melee',
        'damage': '2d4',
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile',
        'details': 'Heavy',
        'misc': '',
        'weight': 10,
        'rarity': 3,
        'cost': 4000
    },
        {
        'name': 'Sling',
        'size': '2h',
        'type': 'Ranged',
        'damage': '1d4',
        'damageType': 'Bludgeoning',
        'range': '30/120',
        'ammunition': 'rocks',
        'conversion': '',
        'details': 'Loading',
        'misc': '',
        'weight': 1,
        'rarity': 1,
        'cost': 50
    },
]
