export default [
    'Smithy',
    'Armor',
    'Forge',
    'Hammer',
    'Tools',
    'Whetstone',
    'Fletcher',
    'Tannery',
    'Chain Mail',
    'Fire',
    'Greaves',
    'Helms',
    'Pauldrons',
    'Blade',
    'Slag',
    'Cobble',
    'Wrought Iron',
    'Firescale',
]