export default [
    {
    'name': 'Kindred',
    'description': 'Circled in the blackmarkets, these items can range from cursed junk to spectacular treasure -- just like the folks who buy them.',
    'cost': 4,
    'dieNumMod': '',
    'dieSizeMod': '',
    'charges': '',
    'cursed': '15%',
    'saveDC': '',
    'abilityWeapon': '',
    'weight': 16,
},
{
    'name': 'Zjadrin',
    'description': 'Extraplanar in origin, these items tend to bear strange and fascinating designs.',
    'cost': 2,
    'dieNumMod': '',
    'dieSizeMod': '+2',
    'charges': '',
    'cursed': '15%',
    'saveDC': '',
    'abilityWeapon': '',
    'weight': 11,
},
{
    'name': 'Vik\'Di',
    'description': 'Typically created by new apprentices and unskilled crafters, these items are of poor quality.',
    'cost': .4,
    'dieNumMod': '',
    'dieSizeMod': '-2',
    'charges': '-1',
    'cursed': '10%',
    'saveDC': '',
    'abilityWeapon': '',
    'weight': 20,
},
{
    'name': 'Bachmol',
    'description': 'Worn down with age and misuse, these items are brittle and less potent than their Silvetta counterpart.',
    'cost': .7,
    'dieNumMod': '',
    'dieSizeMod': '',
    'charges': '1',
    'cursed': '15%',
    'saveDC': '',
    'abilityWeapon': 'Halve all charge regeneration and all damage dealt by this weapon. On an attack roll of 1, the weapon is damaged and considered an Improvised Weapon until repaired.',
    'weight': 10,
},
{
    'name': 'Silvetta',
    'description': 'Bog standard items created by skilled crafters.',
    'cost': 1,
    'dieNumMod': '',
    'dieSizeMod': '',
    'charges': '',
    'cursed': '10%',
    'saveDC': '',
    'abilityWeapon': '',
    'weight': 40,
},
{
    'name': 'Echroel',
    'description': 'Dazzling masterpieces, unparalelled in beauty and design, these items tend to have names and bear the stamp of their (usually deceased) creator.',
    'cost': 230,
    'dieNumMod': '*2',
    'dieSizeMod': '',
    'charges': '*2',
    'cursed': '50%',
    'saveDC': '+1',
    'abilityWeapon': '',
    'weight': 3,
},
{
    'name': 'Cursed',
    'description': 'This item is cursed.',
    'cost': 0,
    'dieNumMod': '',
    'dieSizeMod': '',
    'charges': '',
    'cursed': '100%',
    'saveDC': '',
    'abilityWeapon': '',
    'weight': 0,
}
]