export default [
    'plains',
    'hills',
    'foothills',
    'mountains',
    'valley',
    'interlocked chasms',
    'ravine',
    'cliffside',
    'canyon',
    'riverside',
    'lakefront',
    'oceanfront',
    'cavern',
    'seaside',
    'forest',
    'rainforest',
    'petrified forest',
    'redwood forest',
    'crystal forest',
    'evergreen forest',
    'forested mountain',
    'bluffs',
    'plateau',
    'desert',
    'tundra',
    'red desert',
    'savannah',
    'grassland',
    'oasis',
    'island',
    'peninsula',
    'atoll',
    'swamp',
    'marsh',
    'strait',
    'waterfall',
    'volcano',
    'geyser',
    'hot springs',
    'land bridge',
    'ancient ruins',
    'boneyard'
]