export default [
    {
        'id': 1,
        'source': 'SRD',
        'name': 'Short Sword',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 6,
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 1000
    },
        {
        'id': 2,
        'source': 'SRD',
        'name': 'Long Sword',
        'size': '1h/2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 8,
        'conversionNumOfDie': 1,
        'conversionDieSize': 10,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile:',
        'details': '',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 1500
    },
        {
        'id': 3,
        'source': 'SRD',
        'name': 'Light Crossbow',
        'size': '2h',
        'type': 'Ranged',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 8,
        'damageType': 'Piercing',
        'range': '80/320',
        'ammunition': 'Bolts',
        'conversion': '',
        'details': 'Loading',
        'misc': '',
        'weight': 5,
        'rarity': 1,
        'cost': 2500
    },
        {
        'id': 4,
        'source': 'SRD',
        'name': 'Hand Crossbow',
        'size': '',
        'type': 'Ranged',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 6,
        'damageType': 'Piercing',
        'range': '30/120',
        'ammunition': 'Bolts',
        'conversion': '',
        'details': 'Loading, Light',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 7500
    },
        {
        'id': 5,
        'source': 'SRD',
        'name': 'Heavy Crossbow',
        'size': '2h',
        'type': 'Ranged',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 10,
        'damageType': 'Piercing',
        'range': '100/400',
        'ammunition': 'Bolts',
        'conversion': '',
        'details': 'Loading, Heavy',
        'misc': '',
        'weight': 18,
        'rarity': 1,
        'cost': 5000
    },
        {
        'id': 6,
        'source': 'SRD',
        'name': 'Long Bow',
        'size': '2h',
        'type': 'Ranged',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 8,
        'damageType': 'Piercing',
        'range': '150/600',
        'ammunition': 'Arrows',
        'conversion': '',
        'details': 'Heavy',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 5000
    },
        {
        'id': 7,
        'source': 'SRD',
        'name': 'Short Bow',
        'size': '2h',
        'type': 'Ranged',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 6,
        'damageType': 'Piercing',
        'range': '80/320',
        'ammunition': 'Arrows',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 2500
    },
        {
        'id': 8,
        'source': 'SRD',
        'name': 'Mace',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 6,
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 500
    },
        {
        'id': 9,
        'source': 'HB',
        'name': 'Cane',
        'size': '1h/2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 6,
        'conversionNumOfDie': 1,
        'conversionDieSize': 8,
        'damageType': 'Bludgeoning',
        'range': '10',
        'ammunition': '',
        'conversion': 'Versatile:',
        'details': 'Reach',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 1000
    },
        {
        'id': 10,
        'source': 'SRD',
        'name': 'Flail',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 8,
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 1000
    },
        {
        'id': 11,
        'source': 'SRD',
        'name': 'Morningstar',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 8,
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 1500
    },
        {
        'id': 12,
        'source': 'SRD',
        'name': 'Rapier',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 8,
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 2500
    },
        {
        'id': 13,
        'source': 'HB',
        'name': 'Bastard Sword',
        'size': '1h/2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 10,
        'conversionNumOfDie': 1,
        'conversionDieSize': 12,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile:',
        'details': 'Heavy',
         'misc': '',
        'weight': 6,
        'rarity': 1,
        'cost': 4000
    },
        {
        'id': 14,
        'source': 'HB',
        'name': 'Knuckle Dusters',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 4,
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Light',
        'misc': 'Hidden: You are considered as proficient with Sleight of Hand while hiding this weapon.',
        'weight': 1,
        'rarity': 1,
        'cost': 200
        },
            {
        'id': 15,
        'source': 'HB',
        'name': 'Clawed Knuckle Dusters',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 6,
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse',
        'misc': 'Hidden: You are considered as proficient with Sleight of Hand while hiding this weapon.',
        'weight': 1,
        'rarity': 1,
        'cost': 1000
    },
        {
        'id': 16,
        'source': 'SRD',
        'name': 'Great Axe',
        'size': '2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 12,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Heavy',
        'misc': '',
        'weight': 7,
        'rarity': 1,
        'cost': 3000
    },
        {
        'id': 17,
        'source': 'SRD',
        'name': 'Handaxe',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 6,
        'damageType': 'Slashing',
        'range': '20/60',
        'ammunition': '',
        'conversion': '',
        'details': 'Light, Thrown',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 500
    },
        {
        'id': 18,
        'source': 'SRD',
        'name': 'Halberd',
        'size': '2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 10,
        'damageType': 'Slashing',
        'range': '10',
        'ammunition': '',
        'conversion': '',
        'details': 'Reach, Heavy',
        'misc': '',
        'weight': 6,
        'rarity': 1,
        'cost': 2000
    },
        {
        'id': 19,
        'source': 'HB',
        'name': 'Polearm',
        'size': '2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 10,
        'damageType': 'Piercing',
        'range': '10',
        'ammunition': '',
        'conversion': '',
        'details': 'Reach, Heavy',
        'misc': '',
        'weight': 18,
        'rarity': 1,
        'cost': 1500
    },
        {
        'id': 20,
        'source': 'SRD',
        'name': 'Dagger',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 4,
        'damageType': 'Piercing',
        'range': '20/60',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse, Light, Thrown',
        'misc': '',
        'weight': 1,
        'rarity': 1,
        'cost': 200
    },
        {
        'id': 21,
        'source': 'HB',
        'name': 'Kris',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 6,
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 1000
    },
        {
        'id': 22,
        'source': 'SRD',
        'name': 'Whip',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 4,
        'damageType': 'Slashing',
        'range': '10',
        'ammunition': '',
        'conversion': '',
        'details': 'Reach, Finesse',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 200
    },
        {
        'id': 23,
        'source': 'SRD',
        'name': 'Sickle',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 4,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 100
    },
        {
        'id': 24,
        'source': 'SRD',
        'name': 'Light Hammer',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 4,
        'damageType': 'Bludgeoning',
        'range': '20/60',
        'ammunition': '',
        'conversion': '',
        'details': 'Light, Thrown',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 200
    },
        {
        'id': 25,
        'source': 'SRD',
        'name': 'Warhammer',
        'size': '1h/2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 8,
        'conversionNumOfDie': 1,
        'conversionDieSize': 10,
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile:',
        'details': '',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 1500
    },
        {
        'id': 26,
        'source': 'SRD',
        'name': 'Net',
        'size': '',
        'type': 'Ranged',
        'proficiency': 'Martial',
        'damageType': 'None',
        'range': '5/15',
        'ammunition': '',
        'conversion': '',
        'details': 'Thrown, Special',
        'misc': 'A large or smaller creature hit by a net is Restrained until it is freed. A net has no effect on creatures that are formless, or creatures that are huge or larger. A creature can use its action to make a DC Strength check, freeing itself or another creature within its reach on a success. Dealing 5 slashing damage to the net (AC 10) also frees the creature without harming it, ending the effect and destroying the net. When you use an action, Bonus Action, or Reaction to attack with a net, you can make only one attack regardless of the number of attacks you can normally make.',
        'saveDC': 10,
        'weight': 3,
        'rarity': 1,
        'cost': 100
    },
        {
        'id': 27,
        'source': 'HB',
        'name': 'Hooked Chain',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 4,
        'damageType': 'Slashing',
        'range': '10',
        'ammunition': '',
        'conversion': '',
        'details': 'Reach, Finesse, Light',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 500
    },
        {
        'id': 28,
        'source': 'SRD',
        'name': 'Spear',
        'size': '1h/2h',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 6,
        'conversionNumOfDie': 1,
        'conversionDieSize': 8,
        'damageType': 'Piercing',
        'range': '20/60',
        'ammunition': '',
        'conversion': 'Versatile:',
        'details': 'Thrown',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 100
    },
        {
        'id': 29,
        'source': 'SRD',
        'name': 'Javelin',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 6,
        'damageType': 'Piercing',
        'range': '30/120',
        'ammunition': '',
        'conversion': '',
        'details': 'Thrown',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 50
    },
        {
        'id': 30,
        'source': 'SRD',
        'name': 'Club',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 4,
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Light',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 10
    },
        {
        'id': 31,
        'source': 'SRD',
        'name': 'Glaive',
        'size': '2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 10,
        'damageType': 'Slashing',
        'range': '10',
        'ammunition': '',
        'conversion': '',
        'details': 'Reach, Heavy',
        'misc': '',
        'weight': 6,
        'rarity': 1,
        'cost': 2000
    },
        {
        'id': 32,
        'source': 'SRD',
        'name': 'Quarter Staff',
        'size': '1h/2h',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 6,
        'conversionNumOfDie': 1,
        'conversionDieSize': 8,
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile:',
        'details': '',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 20
    },
        {
        'id': 33,
        'source': 'SRD',
        'name': 'Lance',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 12,
        'damageType': 'Piercing',
        'range': '10',
        'ammunition': '',
        'conversion': '',
        'details': 'Reach, Special',
        'misc': 'You have disadvantage when you use a lance to attack a target within 5 feet of you. Also, a lance requires two hands to wield when you aren’t mounted.',
        'weight': 6,
        'rarity': 1,
        'cost': 1000
    },
        {
        'id': 34,
        'source': 'SRD',
        'name': 'Maul',
        'size': '2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 2,
        'dieSize': 6,
        'damageType': 'Bludgeoning',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Heavy',
        'misc': '',
        'weight': 10,
        'rarity': 1,
        'cost': 1000
    },
        {
        'id': 35,
        'source': 'SRD',
        'name': 'Pike',
        'size': '2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 10,
        'damageType': 'Piercing',
        'range': '10',
        'ammunition': '',
        'conversion': '',
        'details': 'Reach, Heavy',
        'misc': '',
        'weight': 18,
        'rarity': 1,
        'cost': 500
    },
        {
        'id': 36,
        'source': 'SRD',
        'name': 'Scimitar',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 6,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 2500
    },
        {
        'id': 37,
        'source': 'SRD',
        'name': 'Trident',
        'size': '1h/2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 6,
        'conversionNumOfDie': 1,
        'conversionDieSize': 8,
        'ddamageType': 'Piercing',
        'range': '20/60',
        'ammunition': '',
        'conversion': 'Versatile:',
        'details': 'Thrown',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 500
    },
        {
        'id': 38,
        'source': 'SRD',
        'name': 'War Pick',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 8,
        'damageType': 'Piercing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 500
    },
        {
        'id': 39,
        'source': 'HB',
        'name': 'Saber',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 8,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse',
        'misc': '',
        'weight': 3,
        'rarity': 1,
        'cost': 3000
    },
        {
        'id': 40,
        'source': 'HB',
        'name': 'Claymore',
        'size': '2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 2,
        'dieSize': 8,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Heavy',
        'misc': '',
        'weight': 8,
        'rarity': 3,
        'cost': 10000
    },
        {
        'id': 41,
        'source': 'HB',
        'name': 'Cutlass',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 8,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': '',
        'details': 'Finesse',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 3000
    },
        {
        'id': 42,
        'source': 'HB',
        'name': 'Khopesh',
        'size': '1h/2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 6,
        'conversionNumOfDie': 1,
        'conversionDieSize': 8,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile:',
        'details': 'Finesse, Light',
        'misc': '',
        'weight': 2,
        'rarity': 3,
        'cost': 3500
    },
        {
        'id': 43,
        'source': 'HB',
        'name': 'Machete',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 6,
        'conversionNumOfDie': 1,
        'conversionDieSize': 8,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile:',
        'details': '',
        'misc': '',
        'weight': 4,
        'rarity': 1,
        'cost': 100
    },
        {
        'id': 44,
        'source': 'HB',
        'name': 'Chakram',
        'size': '',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 1,
        'dieSize': 8,
        'damageType': 'Slashing',
        'range': '20/60',
        'ammunition': '',
        'conversion': 'Thrown',
        'details': 'Finesse, Light, Thrown',
        'misc': '',
        'weight': 2,
        'rarity': 1,
        'cost': 3000
    },
        {
        'id': 45,
        'source': 'SRD',
        'name': 'Blowgun',
        'size': '',
        'type': 'Ranged',
        'proficiency': 'Martial',
        'damage': '1',
        'damageType': 'Piercing',
        'range': '25/100',
        'ammunition': 'Darts',
        'conversion': '',
        'details': 'Loading',
        'misc': '',
        'weight': 1,
        'rarity': 1,
        'cost': 1000
    },
        {
        'id': 46,
        'source': 'HB',
        'name': 'Scythe',
        'size': '1h/2h',
        'type': 'Melee',
        'proficiency': 'Martial',
        'numOfDie': 2,
        'dieSize': 4,
        'conversionNumOfDie': 2,
        'conversionDieSize': 6,
        'damageType': 'Slashing',
        'range': '',
        'ammunition': '',
        'conversion': 'Versatile:',
        'details': 'Heavy',
        'misc': '',
        'weight': 10,
        'rarity': 3,
        'cost': 5500
    },
        {
        'id': 47,
        'source': 'SRD',
        'name': 'Sling',
        'size': '',
        'type': 'Ranged',
        'proficiency': 'Simple',
        'numOfDie': 1,
        'dieSize': 4,
        'damageType': 'Bludgeoning',
        'range': '30/120',
        'ammunition': 'Rocks',
        'conversion': '',
        'details': '',
        'misc': '',
        'weight': 1,
        'rarity': 1,
        'cost': 50
    },
]
